<a href="https://colab.research.google.com/github/keerthikapopuri/computational-statistics-lab/blob/main/user_defined_functions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

determinant

In [8]:
#determinant of matrix
import numpy as np
def cofactor(a,i,j):
  temp=np.concatenate((a[:i,:j],a[:i,j+1:]),axis=1)
  new=np.concatenate((a[i+1:,:j],a[i+1:,j+1:]),axis=1)
  return np.concatenate((temp,new))
def det_of(a):
  if(len(a)==2):
    val=(a[0][0]*a[1][1])-(a[0][1]*a[1][0])
  elif(len(a)==1):
    val=a
  else:
    val=0
    for col in range(len(a)):
      sign=(-1)**col
      sub_det=det_of(cofactor(a,0,col))
      val+=(sign*a[0][col]*sub_det)
  return val
a=np.array([[6,9,1],[2,3,8],[10,7,9]])
#finding determinant
print(det_of(a))
print(a)
print(cofactor(a,1,2))

368
[[ 6  9  1]
 [ 2  3  8]
 [10  7  9]]
[[ 6  9]
 [10  7]]


transpose

In [9]:
import numpy as np
def transpose(a):
  rows,cols=a.shape
  new=np.zeros((cols,rows),dtype=float)
  for i in range(rows):
    for j in range(cols):
      new[j][i]=a[i][j]
  return new
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(transpose(a))
print(a)

[[1. 4. 7.]
 [2. 5. 8.]
 [3. 6. 9.]]
[[1 2 3]
 [4 5 6]
 [7 8 9]]


multiplication of matrices

In [10]:
import numpy as np
def multiply(a,b):
  row1,col1=a.shape
  row2,col2=b.shape
  new=np.zeros((row1,col2),dtype=float)
  for i in range(row1):
    for j in range(col2):
      for k in range(col1):
        new[i][j]=new[i][j]+(a[i][k]*b[k][j])
  return new
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
b=np.array([[9,8,7],[6,4,5],[3,2,1]])
print(multiply(a,b))

[[ 30.  22.  20.]
 [ 84.  64.  59.]
 [138. 106.  98.]]


adjoint matrix

In [11]:
import numpy as np
def adjoint(a):
  rows,cols=a.shape
  sign=[+1.0,-1.0]
  temp=0
  adj=np.empty([rows,cols],dtype=float)
  for i in range(rows):
    if(i%2==0):
        temp=0
    else:
      temp=1
    for j in range(cols):
      if(temp==0):
        mul=sign[0]
        temp=1
      else:
        mul=sign[1]
        temp=0
      co=cofactor(a,i,j)
      val=det_of(co)
      #print(val)
      val=val*mul
      #print(mul)
      adj[i][j]=val
    
  return adj
a=np.array([[1,2,3],[4,5,6],[7,8,9]])
adj=adjoint(a)
print(adj)

[[ -3.   6.  -3.]
 [  6. -12.   6.]
 [ -3.   6.  -3.]]


inverse of a matrix

In [12]:
def inverse(a):
  adj=adjoint(a)
  tran=transpose(adj)
  det=det_of(a)
  inv=tran/det
  return inv

a=np.array([[1,2,7],[4,5,6],[7,10,9]])
inv=inverse(a)
print(inv)

[[-0.46875  1.625   -0.71875]
 [ 0.1875  -1.25     0.6875 ]
 [ 0.15625  0.125   -0.09375]]
